### ISSUE TITLE
dotnet-watch crashes when packages not restored

### ISSUE THREAD

**Issue by breyed** [aspnet/dotnet-watch#154]
1. Add `"Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final"` to `tools` in `project.json`.
2. Don't run `dotnet restore`.
3. Run `dotnet watch`.

This text appears followed by an APPCRASH event for `dotnet.exe`:

````
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Me\.nuget\packages\.tools\Microsoft.DotNet.Watcher.Tools'.
   at System.IO.Win32FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.Win32FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler)
   at System.IO.Win32FileSystemEnumerableFactory.CreateFileNameIterator(String path, String originalUserPath, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Win32FileSystem.EnumeratePaths(String fullPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)
   at System.IO.Directory.EnumerateFileSystemNames(String path, String searchPattern, SearchOption searchOption, Boolean includeFiles, Boolean includeDirs)
   at System.IO.Directory.EnumerateDirectories(String path)
   at Microsoft.DotNet.Cli.Utils.ToolPathCalculator.GetAvailableToolVersions(String packageId)
   at Microsoft.DotNet.Cli.Utils.ToolPathCalculator.GetBestLockFilePath(String packageId, VersionRange versionRange, NuGetFramework framework)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFilePath(LibraryRange toolLibrary, String nugetPackagesRoot)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.GetToolLockFile(LibraryRange toolLibrary, String nugetPackagesRoot)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromToolLibrary(LibraryRange toolLibraryRange, String commandName, IEnumerable`1 args, ProjectContext projectContext)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveCommandSpecFromAllToolLibraries(IEnumerable`1 toolsLibraries, String commandName, IEnumerable`1 args, ProjectContext projectContext)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(String commandName, IEnumerable`1 args, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
````

**Comment by victorhurdugaci** [comment]
This is a dotnet CLI issue. It would happen with any tool, not just `dotnet-watch`. I suggest looking at the issues [here](https://github.com/dotnet/cli) if it was already reported.

**Comment by breyed** [comment]
It looks like it's already reported as dotnet/cli#4034.
