### ISSUE TITLE
dotnet watch -> FileNotFoundException

### ISSUE THREAD

**Issue by gabrielrobert** [aspnet/dotnet-watch#160]
Is there any dependencies (like `Microsoft.DotNet.ProjectModel`) I need to install to use dotnet-watch?

I can't run any dotnet-watch command:

```
{
  "dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.SqlServer.Design": {
      "version": "1.0.0",
      "type": "build"
    },
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.1",
    "Microsoft.AspNetCore.Identity": "1.0.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    },
    "Microsoft.DotNet.Watcher.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net451+win8"
    }
  },

  "frameworks": {
    "net461": {}
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": "log4net.config"
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "config.json",
      "web.config",
      "log4net.config",
      "Logs"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

```
dotnet --info
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at Microsoft.DotNet.Watcher.Tools.Program.<>c__DisplayClass3_0.<MainInternal>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Watcher.Tools.Program.MainInternal(String[] args, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.Program.Main(String[] args)
```

Thank you.

**Comment by BrennanConroy** [comment]
Did you do a successful `dotnet restore` before trying to use the watcher?

**Comment by gabrielrobert** [comment]
Every time I compile, I use this simple but effective command:

`rimraf project.lock.json & dotnet restore & dotnet watch run`

Which result in:

```
rimraf project.lock.json & dotnet restore & dotnet watch run
log  : Restoring packages for C:\dev\test\Test.Web\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in C:\dev\test\Test.Web\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in C:\dev\test\Test.Web\project.json...
log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools' in C:\dev\test\Test.Web\project.json...
log  : Restoring packages for tool 'Microsoft.VisualStudio.Web.CodeGeneration.Tools' in C:\dev\test\Test.Web\project.json...
log  : Restoring packages for tool 'Microsoft.DotNet.Watcher.Tools' in C:\dev\test\Test.Web\project.json...
log  : Writing lock file to disk. Path: C:\dev\test\Test.Web\project.lock.json
log  : C:\dev\test\Test.Web\project.json
log  : Restore completed in 10640ms.
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.ProjectModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
   at Microsoft.DotNet.Watcher.Tools.Program.<>c__DisplayClass3_0.<MainInternal>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Watcher.Tools.Program.MainInternal(String[] args, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.Program.Main(String[] args)
"String1:""	"
```

**Comment by victorhurdugaci** [comment]
Use `1.0.0-preview2-final` for the dotnet watch version. That's a problem already being investigated: https://github.com/aspnet/dotnet-watch/issues/147

**Comment by gabrielrobert** [comment]
@victorhurdugaci Still having the same problem after using `rimraf project.lock.json & dotnet restore & dotnet watch run`. Could it be environment problem?

```
"tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    },
    "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final"
  }
```

**Comment by victorhurdugaci** [comment]
Try deleting the `%userprofile%\.nuget` and `%localappdata%\NuGet\v3-cache` folders, then restore again. If that doesn't solve the problem, let me know.

**Comment by gabrielrobert** [comment]
@victorhurdugaci Still got the same problem. I also removed any .CORE references from "Add/Remove program" and reinstalled it from here: https://www.microsoft.com/net/core#windows

`rimraf %userprofile%\.nuget & rimraf %localappdata%\NuGet\v3-cache & rimraf project.lock.json & dotnet restore & dotnet watch run`

![image](https://cloud.githubusercontent.com/assets/5783827/18332620/206f4e70-7536-11e6-9451-3add8e2668f3.png)

**Comment by gabrielrobert** [comment]
```
"tools": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    },
    "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final"
  }
```

**Comment by perokvist** [comment]
Just removing all versions of %userprofile%\.nuget\packages\.tools\Microsoft.DotNet.Watcher.Tools\ and restore worked for me. Had both preview 1 and 2.
